### ISSUE TITLE
Update gulp-autoprefixer to v4.0.0

### ISSUE THREAD

**Issue by jennifer-shehane** [chrisbreiding/zunder#3]
I get this error whenever I use any `flex` css styling in my project. I believe it was an error coming from [autoprefixer](https://github.com/postcss/autoprefixer) which is a dependency of [gulp-autoprefixer](https://github.com/sindresorhus/gulp-autoprefixer) which has since been fixed in their 4.0.0 version. I didn't update it to completely verify this though, just checked existing issues.

```bash
gulp-autoprefixer: 
  autoprefixer: /project-name/main.css:13642:3: You should write display: flex by final spec instead of display: box
```

**Comment by chrisbreiding** [comment]
Fixed in `5.4.1`.

**Comment by jennifer-shehane** [comment]
I'm still getting this error in 5.4.3, although I see that you have gulp-autoprefixer v 4.0.0 :(

```
[16:10:42] gulp-autoprefixer: 
  autoprefixer: /Users/jennifer/Dev/Projects/cypress-dashboard/src/main.css:4:31277: You should write display: flex by final spec instead of display: box
```

```
$ npm ls gulp-autoprefixer
cypress-dashboard@1.5.8 /Users/jennifer/Dev/Projects/cypress-dashboard
└─┬ zunder@5.4.3
  └── gulp-autoprefixer@4.0.0 
```

**Comment by chrisbreiding** [comment]
Yeah, I didn't really verify anything, just bumped the version. Will have to look deeper into it.

**Comment by chrisbreiding** [comment]
Looks like you're getting that error because you're using `display: box`  😅
